title = "Config File"

[database]
name = "streamline_dev"
host = "localhost"
user = "postgres"
password = ""

[server]
port = "8080"
ginMode = "debug" # set to "release" in prod
hmacSecret = "asd23sfkljdjffddsf"